"""Tables for Paper 2, regenerated from the results files into paper2/tables/*.tex.

    python paper2/make_tables.py

tab_liveness   live vectors per recipe at each session's gate, and the released recipe (S-1M)
tab_health     each health check's AUC at telling live from dead vectors (S-2, S-1, P2-L)
tab_dose       next-token KL at the same fraction of the residual norm, and real against random
               KL on the KL-calibrated grid (P2-D)
tab_yesbias    P2-F: factual-NO against introspective P(YES) change at the same arm and dose
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(HERE, "tables")
os.makedirs(OUT, exist_ok=True)
S2 = [("Qwen2.5-3B", "s2_qwen3b"), ("Qwen2.5-7B", "s2_qwen7b"), ("Gemma-3-4B (KL grid)", "s2_gemma4b_kl")]
S1 = [("Gemma-3-12B (4-bit)", "s1_gemma12"), ("Gemma-3-27B (4-bit)", "s1_gemma27")]


def load(p):
    return json.load(open(os.path.join(ROOT, p), encoding="utf-8"))


def rows(p):
    return [json.loads(l) for l in open(os.path.join(ROOT, p), encoding="utf-8") if l.strip()]


def write(name, body):
    with open(os.path.join(OUT, f"{name}.tex"), "w", encoding="utf-8") as f:
        f.write("% Generated by paper2/make_tables.py; do not edit by hand.\n" + body)


def tab_liveness():
    lines = []
    for name, stem in S2:
        a = load(f"results/{stem}_analysis.json")["live_by_arm"]
        c, t, s = (a["concept token"], a["template tail"], a["sentence mean"])
        lines.append(f"{name} & S-2 & {c[0]}/{c[1]} & {t[0]}/{t[1]} & {s[0]}/{s[1]} \\\\")
    for name, stem in S1:
        g = load(f"results/{stem}_analysis.json")["cells"]["4bit"]["pass_rate"]["0.5 nat (gate)"]
        lines.append(f"{name} & S-1 & {g['concept'][0]}/{g['concept'][1]} & {g['tail'][0]}/{g['tail'][1]} & "
                     f"{g['sentence'][0]}/{g['sentence'][1]} \\\\")
    R = rows("results/s1_gemma27/s1_gemma27_s1m_steer_macar-release.jsonl")
    base = {r["concept"]: r["steered"] for r in R if r["alpha"] == 0}
    live = sum(1 for r in R if r["alpha"] == 4 and r["steered"] and not base[r["concept"]])
    lines.append(f"Gemma-3-27B, released recipe and strength 4 & S-1M & --- & {live}/30 & --- \\\\")
    write("tab_liveness", "\\begin{tabular}{llccc}\n\\toprule\nmodel & study & concept token & "
          "template tail & sentence mean \\\\\n\\midrule\n" + "\n".join(lines) +
          "\n\\bottomrule\n\\end{tabular}\n")


def tab_health():
    checks = ["norm", "distinctness", "stability", "probe", "logit steering", "P(YES) shift"]
    lap = load("results/p2l_logit_lens_health.json")
    fmt = lambda v: f"{v['auc']:.2f}" + (f" [{v['ci95'][0]:.2f}, {v['ci95'][1]:.2f}]" if "ci95" in v else "")
    lines = []
    for name, stem in S2:
        a = load(f"results/{stem}_analysis.json")
        cells = [fmt(a["auc"][c]) for c in checks]
        l = lap[f"S-2 {name.replace(' (KL grid)', ', KL grid')}"]
        lines.append(f"{name} ({a['live']}/{a['vectors']}) & " + " & ".join(cells) + f" & {fmt(l)} \\\\")
    a = load("results/s1_gemma12_analysis.json")["cells"]["4bit"]
    h = a["health_auc_at_gate"]
    live = sum(n for n, _ in a["pass_rate"]["0.5 nat (gate)"].values())
    cells = [f"{h[c]:.2f}" if c in h else "---" for c in checks]
    l = lap["S-1 Gemma-3-12B, 4-bit"]
    lines.append(f"Gemma-3-12B, 4-bit ({live}/90) & " + " & ".join(cells) + f" & {fmt(l)} \\\\")
    head = " & ".join(["model (live)"] + checks + ["logit-lens accessibility"])
    write("tab_health", "\\begin{tabular}{l" + "c" * (len(checks) + 1) + "}\n\\toprule\n" + head +
          " \\\\\n\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")


def tab_dose():
    d = load("results/p2d_dose_transfer.json")
    t = d["transfer_at_same_fraction"]
    fr = [0.25, 0.5, 1.0]
    lines = []
    for name, pts in t.items():
        kl = {p["fraction"]: p["median_kl"] for p in pts}
        lines.append(f"{name} & " + " & ".join(f"{kl[f]:.3g}" for f in fr) + " \\\\")
    g = d["real_vs_random_on_kl_grid"]
    grid = " & ".join(f"{p['target_nats']:g}" for p in g)
    ratio = " & ".join(f"{p['concept_over_random']:.2f}" for p in g)
    write("tab_dose", "\\begin{tabular}{lccc}\n\\toprule\nfraction of residual norm & 0.25 & 0.5 & 1.0 \\\\\n\\midrule\n" +
          "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n\n\\medskip\n\n"
          "\\begin{tabular}{l" + "c" * len(g) + "}\n\\toprule\nGemma-3-4B, KL target (nats) & " + grid +
          " \\\\\n\\midrule\nconcept KL / random KL & " + ratio + " \\\\\n\\bottomrule\n\\end{tabular}\n")


def tab_yesbias():
    d = load("results/p2f_analysis.json")
    lines = []
    for name, rs in d.items():
        model, arm = name.split(" / ")
        for r in rs:
            lines.append(f"{model.split(' (')[0]} & {arm} & {r['dose']} & {r['median_kl']:.3g} & "
                         f"{r['introspective_change']:+.3f} & {r['factual_no_change']:+.3f} & "
                         f"{r['ratio']:.3f} \\\\")
    write("tab_yesbias", "\\begin{tabular}{lllcccc}\n\\toprule\nmodel & vectors & dose & median KL & "
          "introspective & factual-NO & ratio \\\\\n\\midrule\n" + "\n".join(lines) +
          "\n\\bottomrule\n\\end{tabular}\n")


if __name__ == "__main__":
    for f in (tab_liveness, tab_health, tab_dose, tab_yesbias):
        f()
    print("wrote", sorted(os.listdir(OUT)))
